---
name: aiidalab-ispg-docker-stack
channels:
    - conda-forge
dependencies:
    - bumpver=2022.1118
    - docker-compose=1.29.2
    - pip=22.2.2
    - pytest=7.1.2
    - requests==2.28.1
    - pip:
          - pytest-docker==1.0.0
