---
name: aiidalab-ispg-docker-stack
channels:
    - conda-forge
dependencies:
    - python=3.11
    - bumpver
    - docker-compose>=1.29.2
    - pip
    - pytest
    - requests
    - pip:
          - pytest-docker
