---
name: aiidalab-ispg-docker-stack
channels:
    - conda-forge
dependencies:
    - bumpver=2023.1129
    - docker-compose=1.29.2
    - pip
    - pytest=7.4.4
    - python=3.11
    - requests=2.31.0
    - pip:
          - pytest-docker==2.0.1
