---
# Build and test all Docker images on every push and pull request.
#
# Builds the images with docker buildx bake and pushes them to a local Docker
# image registry, and runs the automated tests with pytest.

name: continuous-integration

on:
    push:
        branches:
            - main
        tags:
            - "*"
    pull_request:
        branches:
            - main

jobs:

    build:

        runs-on: ubuntu-latest
        timeout-minutes: 20

        #outputs:
        #    images: ${{ steps.bake_metadata.outputs.images }}

        steps:
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v4
              with:
                images: ghcr.io/${{ github.repository }}
                tags: latest
            - name: Build image
              id: build
              uses: docker/build-push-action@v3
              with:
                  tags: ${{ steps.meta.outputs.tags }}
                  push: true

    test:
        needs: build
        if: false

        runs-on: ubuntu-latest
        timeout-minutes: 10

        steps:
            - uses: actions/checkout@v2
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Setup Python test environment
              uses: mamba-org/provision-with-micromamba@v13
              with:
                  cache-env: true
            - name: Run tests
              shell: bash -l {0}  # required to activate the conda environment
              #env: ${{ fromJSON(needs.build.outputs.images) }}
              run: |
                  pytest -v
