---
# Build and test the ATMOSPEC Docker image on every push and pull request.
# Publishes Docker images to Github Container Repository (ghcr.io),
# and runs the automated tests with pytest.

name: Docker

on:
    push:
        branches:
            - main
    pull_request:
    release:
        types: [published]

env:
    REGISTRY: ghcr.io/
    ISPG_IMAGE: ${{ github.repository_owner }}/atmospec

jobs:

    build:

        runs-on: ubuntu-22.04
        timeout-minutes: 20
        permissions:
            packages: write
            contents: read
        outputs:
            image_digest: ${{ steps.build.outputs.digest }}

        steps:
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build image
              id: build
              uses: docker/build-push-action@v5
              with:
                  tags: ${{ env.REGISTRY }}${{ env.ISPG_IMAGE }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
                  outputs: |
                      type=registry,push-by-digest=true,name-canonical=true

    test:
        needs: build
        runs-on: ubuntu-22.04
        timeout-minutes: 10
        permissions:
            packages: read
            contents: read

        steps:
            - uses: actions/checkout@v4
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Setup Python test environment
              uses: mamba-org/setup-micromamba@v1
              with:
                  environment-file: environment.yml
                  cache-environment: true

            - name: Run tests
              shell: bash -l {0}  # required to activate the conda environment
              run: pytest -vs
              env:
                  # Image that was build in the build workflow
                  ISPG_IMAGE: ${{ env.ISPG_IMAGE }}@${{ needs.build.outputs.image_digest }}

    release-ghcr:
        if: github.repository_owner == 'ispg-group'
        needs: [build, test]
        uses: ./.github/workflows/publish.yml
        with:
            image_digest: ${{ needs.build.outputs.image_digest}}
            registry: ghcr.io
        secrets: inherit
        permissions:
            packages: write
            contents: write
