---
name: Publish images to Docker container registries

env:
    # https://github.com/docker/metadata-action?tab=readme-ov-file#environment-variables
    DOCKER_METADATA_PR_HEAD_SHA: true

on:
    workflow_call:
        inputs:
            image_digest:
                description: Digest of image built in build step
                required: true
                type: string
            registry:
                description: Docker container registry
                required: true
                type: string

jobs:

    release:
        runs-on: ubuntu-22.04
        timeout-minutes: 30

        steps:
            - uses: actions/checkout@v4

            - name: Login to GitHub Container Registry 🔑
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Login to DockerHub 🔑
              uses: docker/login-action@v3
              if: inputs.registry == 'docker.io'
              with:
                  registry: docker.io
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v5
              env: ${{ fromJSON(steps.build_vars.outputs.vars) }}
              with:
                  # e.g. ghcr.io/aiidalab/full-stack
                  images: ${{ inputs.registry }}/${{ env.ISPG_IMAGE }}
                  tags: |
                      type=ref,event=pr
                      type=edge,enable={{is_default_branch}}
                      type=match,pattern=v(\d{4}\.\d{2}.\d+(-.+)?),group=1

            - name: Push image
              uses: akhilerm/tag-push-action@v2.2.0
              with:
                  src: ${{ inputs.registry }}/${{ env.ISPG_IMAGE }}@${{ inputs.image_digest }}
                  dst: ${{ steps.meta.outputs.tags }}
